language: python
sudo: false
cache: pip

matrix:
  include:
    - python: '3.4'
      env: DJANGO2="django>=2.0,<2.1"
    - python: '3.5'
      env: DJANGO2="django>=2.0,<2.1"
    - python: '3.6'
      env: DJANGO2="django>=2.0,<2.1"

# command to install requirements
install:
  - pip install https://github.com/netjson/django-netjsongraph/tarball/master
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8
  - ./runisort

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=openwisp_network_topology runtests.py

after_success:
  coveralls
